[Feat] iOS 파트 1차 과제
30th-THE-SOPT-iOS-Part/LeeEuiJin pull request #3
Opened 2022-04-09 19:48 UTC by lee-euijin

## 🌱 작업한 내용

- 로그인 화면 UI 구성
- 회원가입 화면 UI 구성

## 🌱 PR Point

1. 비활성화된 버튼의 title 색이 흰 색이 아닌 진회색이 뜨는데 setTitle 등을 사용해도 변하지 않습니다. 이에 대한 해결방법이 궁금합니다.
2. 가입 화면에서 입력된 이름을 (VC1) 비밀번호 입력 화면 (VC2)를 지나, 확인 화면 (V3)에서 출력할 때, VC1의 textField 입력을, VC2로 넘기고, 다시 VC2에 넘겨진 값을 VC3로 넘기는 방식으로 구현하였는데 이 방식이 맞을까요?

## 📸 스크린샷

|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| 로그인 화면 기능 구현 |![로그인 화면](https://user-images.githubusercontent.com/60493070/162589284-f15a5038-f308-4ea5-b4ac-15eb4e9ba2bb.gif)|
| 로그인 화면 입력 -> 확인 화면|![로그인to확인](https://user-images.githubusercontent.com/60493070/162589308-f2be572e-ceaa-4450-93c7-d1477d1e3867.gif)|
| 가입하기 |![가입하기](https://user-images.githubusercontent.com/60493070/162589344-707f18ee-a5b5-42a0-955d-e4edd2d95541.gif)|
| 가입화면 - 뒤로 가기|![가입화면pop](https://user-images.githubusercontent.com/60493070/162589358-712de8c9-465a-42fc-9ea5-6c5ab42ca3f9.gif)|

## 📮 관련 이슈

- Resolved: #2

2022-04-10 07:19 UTC, jane1choi reviewed
추가로 PR Point에 남겨준 것들에 대해 답변 조금 남겨보자면..! 
> 비활성화된 버튼의 title 색이 흰 색이 아닌 진회색이 뜨는데 setTitle 등을 사용해도 변하지 않습니다. 이에 대한 해결방법이 궁금합니다.

요부분은 스토리보드에서 어떤 설정을 해줬는지 봐야 해결방법을 알 수 있을 것 같은데,
해결이 안된다면 스토리보드 같이보고 도와드리겠습니다!

> 가입 화면에서 입력된 이름을 (VC1) 비밀번호 입력 화면 (VC2)를 지나, 확인 화면 (VC3)에서 출력할 때, VC1의 textField 입력을, VC2로 넘기고, 다시 VC2에 넘겨진 값을 VC3로 넘기는 방식으로 구현하였는데 이 방식이  맞을까요?

요 질문은 소진님이 남겨주신 질문과 똑같아서 요기에도 쇽샥해올게요~!
데이터 전달 방식에 정답은 없는 것 같아요! 본인이 생각하기에 효율적인 방식으로 데이터를 전달하면 된다고 생각하는데, 
우리가 1주차 세미나에서는 프로퍼티를 이용한 VC간 화면 전달 방법밖에 배우지 않았기 때문에
구현하신 방법 너무 잘했다고 생각해요!(저도 이 방법으로 구현했습니다)
그런데 일반적인 데이터 전달 방법에 더 궁금하다고 하셔서 몇가지 남겨볼게요!

특히 `userName`과 같이 앱 내에서 전역적으로 많이 쓰이는 값을 효율적으로 저장하고, 꺼내 쓸 수 있는 방법에 
`UserDefault`와 싱글톤 패턴 이렇게 두 가지 좋은 방법이 있다고 생각하는데요,
간단하게 설명하자면 `UserDefault`는 앱 내 데이터 저장소라고 할 수 있을 것 같고, 
싱글톤 패턴은 디자인 패턴 중 생성 패턴에 해당하는 디자인 유형으로 클래스가 여러 차례 호출되더라도 딱 한 객체만 생성되기 때문에
객체를 하나만 생성하여 여러 곳에서 공용으로 사용하고 싶을 때 사용하는 디자인 패턴이라고 할 수 있을 것 같아요!
더 자세한 내용이 궁금하실 수 있으니 제가 티스토리에 정리해놓은 자료 링크 두고 가겠습니다! 참고하시면 좋을 것 같아요😊
https://janechoi.tistory.com/2
https://janechoi.tistory.com/4

1차 과제 너무 수고하셨습니다🔥
남겨준 리뷰 참고해서 리팩토링까지 해보면 너무 좋을 것 같습니다😆😊

2022-04-10 07:19 UTC, jane1choi commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +class FirstViewController: UIViewController {
지금 우리 과제에서는 로그인 뷰, 회원가입 1, 회원가입 2와 같이 나와있어 이렇게 네이밍한 것 같은데
`FirstViewController`, `SecondViewController`와 같은 클래스 네이밍은 좋은 네이밍 방법은 아니라고 생각합니다!

좋은 네이밍의 기준이 사람마다 다를 수 있지만, 개인적으로 저는 공동 협업자가 클래스 이름, 함수 이름만 보고도 
이 클래스가 어떤 뷰, 혹은 어떤 기능에 대한 함수인지 직관적으로 판단할 수 있는 네이밍이 좋다고 생각해요!
ex) `LoginViewController`, `SignInViewController`, `resetTextField()`

조금 더 직관적인 네이밍에 대해 고민해보고 리팩토링해보면 좋을 것 같습니다😊😊

2022-04-10 07:19 UTC, jane1choi commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +    override func viewDidLoad() {
`@IBOutlet`과 viewDidLoad() 사이에 한 줄 띄워서 구분해주면 더 직관적인 코드가 될 것 같습니다!

```Swift
// MARK: - @IBOutlet
@IBOutlet weak var tabNextBtn: UIButton!
@IBOutlet weak var userName: UITextField!

// MARK: - Life Cycle
override func viewDidLoad() {

}
```
그리고 위와 같이 마크구문을 활용해서 코드의 직관성을 높이는 것도 좋을 것 같아요!

2022-04-10 07:19 UTC, jane1choi commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +        self.navigationController?.navigationBar.backIndicatorTransitionMaskImage = UIImage(named: "icn_back_24")
`viewDidLoad()`와 같은 생명 주기 함수 안에는 함수 호출 구문만 써주는 것이 좋습니다!(코드의 가독성을 위해)
그래서 협업 시 대부분 기본 컨벤션으로 가져가는 것 같아요! 
요부분의 경우 기능단위로 함수화 시켜서 해당 함수를  `viewDidLoad()`안에서 호출만 하는 방식으로 바꿔봅시다!

```Swift

// MARK: - Life Cycle
override func viewDidLoad() {
        super.viewDidLoad()
        configureUI()
        setUpTextField()
    }

// MARK: - Custom Methods
private func configureUI() {
         self.navigationController?.navigationBar.topItem?.title=""
         self.navigationController?.navigationBar.backIndicatorImage = UIImage(named: "icn_back_24")
         self.navigationController?.navigationBar.backIndicatorTransitionMaskImage = UIImage(named: "icn_back_24")
         self.navigationController?.navigationBar.tintColor = .black
         tabNextBtn.isEnabled = false
         tabNextBtn.backgroundColor = UIColor(displayP3Red: 100/255, green: 150/255, blue: 250/255, alpha: 1)
        }

private func setUpTextField() {
         self.userName.addTarget(self, action: #selector(self.textFieldDidChange(_:)), for: .editingChanged)
        }
```
예를 들면 이런 방식으로요! 이렇게 기능단위로 함수화 해놓는다면, 코드 가독성이 높아질 뿐만 아니라 같은 기능이 필요한
다른 위치에서 함수호출로 해당 기능을 적용해줄 수 있어 코드 효율성도 높아진다는 장점이 있을 것 같아요!
위의 코드는 예시일 뿐이니, 의진님이 네이밍이나 함수단위에 대해 더 고민해보고 다르게 바꿔봐도 좋습니다😊😊

2022-04-10 07:19 UTC, jane1choi commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +    }
불필요한 공백이나 주석은 삭제해줍시다!

2022-04-10 07:19 UTC, jane1choi commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +        if userName.hasText == true {
`hasText`활용 너무 좋습니다👍🏻🔥
비슷한 처리방법으로 `textField.text?.isEmpty`도 있으니 참고해보면 좋을 것 같아요!

2022-04-10 07:19 UTC, jane1choi commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +    @IBOutlet weak var userName: UITextField!
컴포넌트에 대한 네이밍을 할 때도 `userName`보다 `userNameTextField` 와 같은 이름이 더 좋은 방법일 것 같아요!
다른 곳에서 접근해서 쓸 때, 혹은 다른 사람이 코드를 읽을 때 어떤 컴포넌트에 대한 처리인지 직관적으로 파악할 수 있으니까요!😊

2022-04-10 07:19 UTC, jane1choi commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +    @IBAction func tabToVC2Btn(_ sender: Any) {
`ViewController`에 대한 네이밍과 함께 요것도 더 직관적으로 바꿔봅시다!

2022-04-10 07:19 UTC, jane1choi commented on Assignment Week1/Assignment Week1/SecondViewController.swift
> +        if let message1 = message1{
`if let`을 이용한 옵셔널 바인딩 너무 잘하셨네요👍🏻

2022-04-10 07:19 UTC, jane1choi commented on Assignment Week1/Assignment Week1/ThirdViewController.swift
> +    */
요렇게 새로운 파일 생성 시 디폴트로 들어있는 주석들도 불필요한 주석이니 지워줍시다!

2022-04-10 07:19 UTC, jane1choi commented on Assignment Week1/Assignment Week1/ThirdViewController.swift
> +    var message2: String?
`message1`, `message2`와 같이 네이밍한 프로퍼티들도 `userName`과 같이 직관적으로 바꿔보는건 어떨까요?

2022-04-10 07:19 UTC, jane1choi commented on Assignment Week1/Assignment Week1/ViewController.swift
> +        self.navigationController?.pushViewController(nextVC, animated: true)
원하는 영역 드래그한 후 `control + i` 눌러서 들여쓰기 라인 맞춰줍시다!

2022-04-10 07:19 UTC, jane1choi commented on Assignment Week1/Assignment Week1/ViewController.swift
> +        }
요부분 처리 너무 잘해주셨는데요!
`isSelected`라는 프로퍼티를 이용해서 판단해주는 방법도 있을 것 같네요!
요친구를 활용해서
~~~Swift
@IBAction func tapPasswordBtn(_ sender: Any) {
         if tabPasswordBtn.isSelected {
             tapPasswordBtn.setImage(UIImage(named:"password_shown"), for: .normal)
             loginPassword.isSecureTextEntry = false
         } else {
            tapPasswordBtn.setImage(UIImage(named:"password_hidden"), for: .normal)
             loginPassword.isSecureTextEntry = true
    }
~~~
이렇게 바꿔줄 수 있겠네요! 이런 방법이 있다~ 정도로 참고만 해주셔도 됩니다😊

`isSelected`에 대한 자세한 내용은 공식문서 참고해봐도 좋을 것 같아요~
https://developer.apple.com/documentation/uikit/uicontrol/1618203-isselected

2022-04-10 07:19 UTC, jane1choi commented on Assignment Week1/Assignment Week1/ViewController.swift
> +    @IBOutlet weak var tabPasswordBtn: UIButton!
`tapPasswordBtn`과 같은 동작을 설명하는 네이밍은 Action에 대한 네이밍으로 더 적합할 것 같아요!
버튼 컴포넌트에 대해서는 `어떤Btn`과 같은 방식이 좋을 것 같습니다! 참고로 저는 `eyeBtn`이런 식으로 네이밍 했습니다!

2022-04-10 14:36 UTC, jane1choi commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +        // Do any additional setup after loading the view.
빈줄 삭제해주시면 좋을 것 같아요!

2022-04-10 14:39 UTC, jane1choi requested changes
> 비활성화된 버튼의 title 색이 흰 색이 아닌 진회색이 뜨는데 setTitle 등을 사용해도 변하지 않습니다. 이에 대한 해결방법이 궁금합니다.

요부분 스보 같이보고 해결해봅시다!
리뷰 확인 부탁드립니다~

2022-04-10 14:39 UTC, jane1choi commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +
요기도!

2022-04-10 14:39 UTC, jane1choi commented on Assignment Week1/Assignment Week1/SecondViewController.swift
> +
요기도 빈줄 삭제 부탁드립니다~!

2022-04-10 14:41 UTC, jane1choi approved these changes
확인했습니다!

2022-04-11 02:07 UTC, jeongkite commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +    override func viewDidLoad() {
오 대박 마크구문 일케 쓰는거구만요😲😲 좋은거 알아갑니다~👍

2022-04-11 02:31 UTC, jeongkite commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +        if userName.hasText == true {
대박 이 코드 완전 깔끔.. 이렇게 if/else 분기 나누는거 보기 너무 좋은 것 같아요!!

2022-04-11 03:49 UTC, jeongkite commented on Assignment Week1/Assignment Week1/SecondViewController.swift
> +        tabNextBtn.titleLabel?.textColor = .white
오 대박 저는 attribute 다 스토리보드에서 설정했는데 코드로 하는 것도 너무 멋지네요!!👍👍

2022-04-11 03:54 UTC, jeongkite commented on Assignment Week1/Assignment Week1/ViewController.swift
> +        }
와 대박 심화과제까지.. 저도 담번엔 심화 과제 도전합니다!! 같이 화이팅해요~~ 😎💪💪

2022-04-11 05:07 UTC, Jihyun247 commented on Assignment Week1/Assignment Week1/ViewController.swift
> +    @IBOutlet weak var tabPasswordBtn: UIButton!
이 부분은 참고했으면 좋겠어서 추가적으로 남깁니다 !
텍스트필드 위에 버튼을 위에 올려 배치시키는 방법도 있지만, 이렇게 하는 경우 텍스트필드에 텍스트를 오른쪽까지 꽉 차게 입력하게 되면 텍스트와 버튼이 겹치는 상황이 발생하겠죠?

텍스트와 버튼이 겹치지 않도록 하고싶다면 textfield의 rightView를 활용하는 방법이 있어요 !
참고 링크 남길게요

textfield의 rightView : https://developer.apple.com/documentation/uikit/uitextfield/1619596-rightview
기본 클리어버튼 한줄 구현 방법 & rightView를 활용한 custom 클리어버튼 : https://woongsios.tistory.com/315

2022-04-11 12:07 UTC, 513sojin approved these changes

2022-04-11 12:07 UTC, 513sojin commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +        if userName.hasText == true {
저는 isEmpty를 활용했는데 hasText를 활용하는 좋은 방법도 배워갑니다 📝

2022-04-11 12:17 UTC, lee-euijin commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +class FirstViewController: UIViewController {
각 컴포넌트의 기능 + 컴포넌트의 종류 순으로 네이밍을 하는 방식이 확실히 코딩 시 직관성을 높이는 것 같아요!
아직 처음 다루는 것이라 익숙치 않아서 네이밍에 대한 고민을 조금 많이 못하고 과제를 마무리한 것 같은데, 조금 더 직관적인 네이밍을 사용할 수 있게 많이 고민해보겠습니다!!

2022-04-11 12:19 UTC, lee-euijin commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +    override func viewDidLoad() {
저도 처음에 MARK 를 어떻게 쓰는 건지 몰랐는데 좋은 정보 알아갑니다!! 
그리고 엑스코드 우측에 아래 그림과 같은 창이 왜 있는 것인지도 잘 알게 된 것 같아요!
![04-11-2022-21 19 18](https://user-images.githubusercontent.com/60493070/162737891-39d528c0-acb3-4b2b-9e8e-34330298115e.jpg)

2022-04-11 12:21 UTC, lee-euijin commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +        self.navigationController?.navigationBar.backIndicatorTransitionMaskImage = UIImage(named: "icn_back_24")
오호 약간 C언어로 치면 Main 함수 내에는 기능 단위에 함수만 넣는 방향으로 짜는 것과 비슷하네용 !! 

확실히 가독성이 높은 것 같습니다 !! 감사합니다 !! :)

2022-04-11 12:24 UTC, lee-euijin commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +        if userName.hasText == true {
@jane1choi 우올 좋은 말 감사합니다!!! 그리구 저 방법으로도 한 번 구현해보겠습니다!
@jeongkite 앗 칭찬 받았다..... 기분 좋아.. ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 감사합니다!!

2022-04-11 12:34 UTC, lee-euijin commented on Assignment Week1/Assignment Week1/ViewController.swift
> +        }
isSelected 라는 프로퍼티를 활용할 수 있군요!!! 감사합니다!!

다음에는 심화과제 같이 해요~~ ㅋㅋㅋㅋ!!

2022-04-11 12:37 UTC, lee-euijin commented on Assignment Week1/Assignment Week1/ViewController.swift
> +    @IBOutlet weak var tabPasswordBtn: UIButton!
@jane1choi 아하! 약간 Action에는 동사형을 지정해주고, Outlet은 명사형으로 지정하는 것이 직관적으로 더 좋은 것이군요!! 감사합니다!! :)

2022-04-11 12:38 UTC, SuwonPabby commented on Assignment Week1/Assignment Week1/ViewController.swift
> +    @IBOutlet weak var tabPasswordBtn: UIButton!
@Jihyun247 오오오 맞네요! 텍스트필드를 가득차게 입력했을 경우에 겹쳐버리는 상황이 있을 수 있군요!! 이를 참조해서 재구현해보겠습니다!!!

2022-04-11 12:39 UTC, lee-euijin commented on Assignment Week1/Assignment Week1/SecondViewController.swift
> +        tabNextBtn.titleLabel?.textColor = .white
@jeongkite 버튼이 비활성화됐을 때의 설정을 해주려다보니까 결국 코드베이스로 접근하게 되어버리더라구요!!! 나중에 코드베이스도 같이 공부해봐요~~ !

2022-04-11 12:41 UTC, lee-euijin commented on Assignment Week1/Assignment Week1/FirstViewController.swift
> +        if userName.hasText == true {
textField. 이렇게 쳤을 때 나오는 목록을 뒤져보다보니까 hasText라는게 있더라구요! 저도 2차 세미나 갔다가 배운 건데 .을 누르고 관련된 프로퍼티가 있는지 찾아보는 것도 좋은 전략인 것 같아요!!

2022-04-21 17:58 UTC, merged