Assignment2
30th-THE-SOPT-iOS-Part/LeeEuiJin pull request #5
Opened 2022-04-22 09:57 UTC by lee-euijin

## 🌱 작업한 내용

- 기존 Assignment Week 1에서 만든 코드를 코드 리뷰를 바탕으로 리팩토링
- 탭바 폴더링 및 구성하기
- 완료하기 화면과 탭 바 화면 연결
- 로그인 화면 오토 레이아웃 적용
- 심화 과제 : 해결 방안
   1.  Login 화면을 Navigation Controller를 이용해 화면 전환을 전부 구성하고, 다른 계정으로 로그인을 눌렀을 때, PopToRootView를 이용하여 쌓인 Stack을 모두 Pop 해준다.   
   2. 완료하기 버튼을 누르면 새로운 RootView로 변경해주는 방식을 활용, 다시 로그인 화면으로 돌아오고자 할 때에도 RootView를 변경해주는 식으로 한다면 Stack이 계속 쌓이는 사례를 방지할 수 있다. 
   
## 🌱 PR Point

- 실제로 피그마에 있는 수치대로 할 경우 실제 화면에서 구현된 모습과 다를 때가 있는데 이럴 때는 개발자가 대략 눈대중으로 진행하나요?!
- Button UI의 경우 스토리보드로 짤 때 글자의 좌측 정렬, 우측 정렬이 잘 안 먹는 경우가 있었습니다. 본래 Default UI는 가급적 스토리보드로 짜는게 좋지만, 이렇게 스토리보드로 잘 안 먹는 경우에는 코드로 짜줘도 괜찮을까요?
- Root View 가 변경되면서 인스타그램처럼 Dissolve 애니메이션을 넣어주고 싶은데 어떻게 하는지 궁금합니다..!

## 📸 스크린샷

|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| 완료하기 시 탭 바로 이동 |![Simulator Screen Recording - iPhone 13 mini - 2022-04-22 at 18 52 11](https://user-images.githubusercontent.com/60493070/164683025-2b05cd4c-c639-4033-90fd-dda8a26e5db0.gif) |
| 탭 바 전환 |![Simulator Screen Recording - iPhone 13 mini - 2022-04-22 at 18 40 17](https://user-images.githubusercontent.com/60493070/164681327-19c481c3-5c46-4625-8c43-0e28b70b65c1.gif)|
| 다른 계정으로 로그인 버튼 구현 |![Simulator Screen Recording - iPhone 13 mini - 2022-04-22 at 18 42 02](https://user-images.githubusercontent.com/60493070/164681462-37bed58e-1570-4426-8cbd-186695077a28.gif)|
| 오토레이아웃과 Navigation 전환 방식이 적용된 UI |![Simulator Screen Recording - iPhone 13 mini - 2022-04-22 at 18 48 26](https://user-images.githubusercontent.com/60493070/164682326-4bc1ed56-13f0-4db2-868a-15df5f40bc71.gif) |

## 📮 관련 이슈

- Resolved: #4

2022-04-24 07:23 UTC, Jihyun247 requested changes
> 실제로 피그마에 있는 수치대로 할 경우 실제 화면에서 구현된 모습과 다를 때가 있는데 이럴 때는 개발자가 대략 눈대중으로 진행하나요?!

저는 눈대중으로 보고 비율로 잡습니다! 절대적인 값으로 잡으면 엄청 작거나 큰 기기에서는 깨지는 경우가 많아서요

> Button UI의 경우 스토리보드로 짤 때 글자의 좌측 정렬, 우측 정렬이 잘 안 먹는 경우가 있었습니다. 본래 Default UI는 가급적 스토리보드로 짜는게 좋지만, 이렇게 스토리보드로 잘 안 먹는 경우에는 코드로 짜줘도 괜찮을까요?

네! 사람마다 다르지만 저는 스토리보드 쓸 때 최대한 스토리보드 인스펙터에서 지정해주지 않고 코드로 지정해줍니다

2022-04-24 07:23 UTC, Jihyun247 commented on Assignment/Assignment/Login/WelcomeViewController.swift
> +        // 여기에서 애니메이션을 주고 싶은데 어떻게 넣지.... ㅠㅠ
> Root View 가 변경되면서 인스타그램처럼 Dissolve 애니메이션을 넣어주고 싶은데 어떻게 하는지 궁금합니다..!
요거보고 저도 코드를 변경해봤어요 !

변경 전
```swift
let tabBarController = TabBarController()
guard let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene else {return}
windowScene.windows.first?.rootViewController = tabBarController
windowScene.windows.first?.makeKeyAndVisible()
```

변경 후
```swift
let tabBarController = TabBarController()
guard let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene, let window = windowScene.windows.first else {return}
                
window.rootViewController = tabBarController
                
UIView.transition(with: window, duration: 0.3, options: .transitionCrossDissolve, animations: {}, completion: nil)
windowScene.windows.first?.makeKeyAndVisible()
```


- UIView에 정의되어 있는 transition 메서드
```swift
@available(iOS 4.0, *)
open class func transition(with view: UIView, duration: TimeInterval, options: UIView.AnimationOptions = [], animations: (() -> Void)?, completion: ((Bool) -> Void)? = nil)
```
매개변수에 어떤 UIView에 트랜지션을 줄 것인지, 애니메이션이 실행되는 시간, 애니메이션옵션 등을 설정해주어서 화면전환 시 애니메이션을 구현할 수 있어요 !

- 버튼을 눌렀을 때의 간단한 애니메이션 등은 보통 UIView.animate 메서드를 많이 사용합니다. 접두어 transition~으로 시작하는 애니메이션은 transition 메서드를 써야 적용된다고 해서 저는 이번에 transition 메서드를 사용했는데, .transitionCrossDissolve 만 예외로 animate를 써도 된다고 하네요 ? 두 메서드 중 맘에드는 것 사용하셔서 수정해보세용
- 참고링크 : https://jinnify.tistory.com/66

2022-04-24 13:54 UTC, jane1choi reviewed
> Button UI의 경우 스토리보드로 짤 때 글자의 좌측 정렬, 우측 정렬이 잘 안 먹는 경우가 있었습니다. 본래 Default UI는 가급적 스토리보드로 짜는게 좋지만, 이렇게 스토리보드로 잘 안 먹는 경우에는 코드로 짜줘도 괜찮을까요?

스보에서 어떻게 설정해줬는지는 잘 모르겠지만,, inspector 영역에서 잘 지정해줬다면 안 먹을 일은 거의 없는것 같긴한데,, 만약에 안 먹는 경우라면 코드로 지정해줘도 좋을 것 같아요! 스타일 차이일 수도 있지만 스토리보드를 사용한다면 스토리보드에서 지정가능한 것들은 모두 스보로 잡아주는 것이 스토리보드의 장점을 최대한 살리는 방법이라고 저는 개인적으로 생각합니다,,

AutoLayout 같은 경우도 여러 기기에서 최대한 똑같이 보이도록 레이아웃을 잡아주는 것이 가장 좋은 방법이겠죠? 어떤 부분은 비율로, 어떤 부분은 절대적인 값으로 잡아줘도 될지는 레이아웃 잡는 연습을 많이 하다보면 감이 잡힐 거라고 생각합니다! 만약에 특정 부분이 특정 기기에서 이상하게 보인다면, 해당 기기 사이즈를 이용해 그 부분만 분기처리해서 적용해주는 방법도 있습니다!

다른 부분은 최고의 선배 지현이가 잘 정리해줬네요👍🏻🔥
2차 과제도 수고하셨습니다😊

2022-04-24 13:54 UTC, jane1choi commented on Assignment/Assignment/Login/LoginViewController.swift
>          if loginEmail.hasText == true && loginPassword.hasText == true {
`hasText` 자체가 Bool타입이기 때문에 `== true`는 생략해줘도 될 것 같아요!
~~~Swift
if loginEmail.hasText && loginPassword.hasText {
    loginBtn.isEnabled = true
  }
~~~
위와 같이 바꿔도 됩니다!

2022-04-24 13:54 UTC, jane1choi commented on Assignment/Assignment/Login/PasswordViewController.swift
> +            nextVC2.isSignUp = true
개인적으로 `nextVC2`, `message1`와 같이 숫자가 들어가는 네이밍은 좋지 않다고 생각합니다.
공동협업자가 변수명, 함수명만 보고도 어떤 역할을 하는 변수, 함수인지 
직관적으로 알 수 있는 더 좋은 네이밍에 대해 더 고민해보면 좋을 것 같아요!

2022-04-24 13:54 UTC, jane1choi commented on Assignment/Assignment/Login/WelcomeViewController.swift
>      // MARK: - Properties
마크구문 잘 쓰셨네요😊 굿굿👍🏻

2022-04-24 13:54 UTC, jane1choi commented on Assignment/Assignment/TabBar/Home/HomeViewController.swift
> +    */
요렇게 파일 생성 시 디폴트로 생기는 주석들은 필요없는 주석이니 지워주면 좋을 것 같습니다!😊

2022-04-25 18:15 UTC, lee-euijin commented on Assignment/Assignment/Login/WelcomeViewController.swift
> +        // 여기에서 애니메이션을 주고 싶은데 어떻게 넣지.... ㅠㅠ
오오오 감사합니다!!!! transition 메서드를 활용해서 보충해보겠습니다!!!! 감사합니다 :)

2022-04-25 18:17 UTC, lee-euijin commented on Assignment/Assignment/Login/LoginViewController.swift
>          if loginEmail.hasText == true && loginPassword.hasText == true {
오호 훨씬 깔끔한 것 같아요!!! 감사합니다!!! :)

2022-04-25 18:18 UTC, lee-euijin commented on Assignment/Assignment/Login/PasswordViewController.swift
> +            nextVC2.isSignUp = true
앗 제가 다른 것은 다 바꿨는데 저기 nextVC 부분은 생각을 못하고 있었네요!!! 수정하겠습니다!!! :)

2022-04-25 18:18 UTC, lee-euijin commented on Assignment/Assignment/Login/WelcomeViewController.swift
>      // MARK: - Properties
덕분에 완전뿌듯....... 😀

2022-04-25 18:19 UTC, lee-euijin commented on Assignment/Assignment/TabBar/Home/HomeViewController.swift
> +    */
넵넵 감사합니다!!! :)

2022-04-26 12:35 UTC, jeongkite commented on Assignment/Assignment/TabBar/Profile/ProfileViewController.swift
> +}
저는 VC 파일을 아직 만들지 않아서 tabbar 관련 파일들 모두 한 폴더에 넣어뒀는데 이렇게 각각 따로 빼는 것도 너무 좋아보여요!! 나중에 만들면 요렇게 해야겠네요~!!😲👍

2022-04-27 00:23 UTC, 513sojin approved these changes

2022-04-27 00:23 UTC, 513sojin commented on Assignment/Assignment/Login/WelcomeViewController.swift
> +        delegate.window?.rootViewController = nextVC
루트뷰 변경해주는 부분 잘보고갑니다👍🏻👍🏻

2022-04-27 00:23 UTC, 513sojin commented on Assignment/Assignment/Login/WelcomeViewController.swift
> +        // 여기에서 애니메이션을 주고 싶은데 어떻게 넣지.... ㅠㅠ
애니메이션까지..! 과제에서 더 나아가서 새로운 기능을 고민하는 모습 넘 멋져요 !! 지현선배가 달아준 부분까지 잘 배워갑니다 👊🏻

2022-04-27 00:23 UTC, 513sojin commented
주어진 과제에서 그치는게 아니라 새로운 기능까지 고민하는 모습 잘 보고갑니다 !! 2차과제도 넘넘 수고하셨어요🔥

2022-04-27 02:28 UTC, Jihyun247 commented on Assignment/Assignment/Login/WelcomeViewController.swift
> +        // 여기에서 애니메이션을 주고 싶은데 어떻게 넣지.... ㅠㅠ
참고링크 다른 링크를 올렸었네요 ... ;; 수정햇슴다

2022-04-27 02:44 UTC, lee-euijin commented on Assignment/Assignment/Login/WelcomeViewController.swift
> +        // 여기에서 애니메이션을 주고 싶은데 어떻게 넣지.... ㅠㅠ
다행히 오늘부터 공부시작!! 오늘 들어가서 열심히 공부해보께요!! :):)

2022-05-09 09:45 UTC, Jihyun247 approved these changes

2022-05-22 13:04 UTC, lee-euijin commented on Assignment/Assignment/Login/WelcomeViewController.swift
> +        // 여기에서 애니메이션을 주고 싶은데 어떻게 넣지.... ㅠㅠ
긴 세월 끝에 드디어 반영완료...

2022-05-22 13:05 UTC, lee-euijin commented on Assignment/Assignment/Login/LoginViewController.swift
>          if loginEmail.hasText == true && loginPassword.hasText == true {
드디어 반영완료..

2022-05-22 13:21 UTC, lee-euijin commented on Assignment/Assignment/TabBar/Profile/ProfileViewController.swift
> +}
이 댓글을 이제야 보았습니다.. 계속 계속 보면서 닫아야하는데.. 이제야 닫습니다..

2022-05-22 13:22 UTC, lee-euijin commented on Assignment/Assignment/Login/WelcomeViewController.swift
> +        delegate.window?.rootViewController = nextVC
늦었지만 캄사합니당 위에 지현이 코드로 바꿨어용

2022-05-23 00:25 UTC, merged